### PR TITLE
Implement compact byte serde

### PR DESCRIPTION
**Pull request by dapplion**
Makes rust shuffle proof serialization:
- compatible with python spec implementation
- compact, removing vec offsets added by ark CanonicalSerialize

### CODE REVIEW

**Comment by kevaundray** [comment]
Might be a bit painful with #19 😅

**Comment by dapplion** [comment]
> Might be a bit painful with #19 😅

Yeah don't worry I can redo on top of #19

**Comment by dapplion** [comment]
- Rebased on top of https://github.com/asn-d6/curdleproofs/pull/19

**Review by asn-d6 — APPROVED** [review]
Thanks!!

**Pull request merged**
